<?xml version="1.0" encoding="utf-8"?><Database Name="StudentDB2" Class="StudentDB2DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-ENTQENF;Initial Catalog=StudentDB2;Integrated Security=True;Trust Server Certificate=True" SettingsObjectName="VotingApp.Properties.Settings" SettingsPropertyName="StudentDB2ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.registerations" Member="registerations">
    <Type Name="registeration">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="age" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="cnic" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="registeration_student" Member="students" ThisKey="Id" OtherKey="Id" Type="student" />
      <Association Name="registeration_Feedback2" Member="Feedback2s" ThisKey="Id" OtherKey="UserId" Type="Feedback2" />
    </Type>
  </Table>
  <Table Name="dbo.Candidates" Member="Candidates">
    <Type Name="Candidate">
      <Column Name="CandidateId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Age" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Party" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="VotingSign" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="Candidate_student" Member="students" ThisKey="CandidateId" OtherKey="CandidateId" Type="student" />
      <Association Name="Candidate_Winner" Member="Winners" ThisKey="CandidateId" OtherKey="CandidateId" Type="Winner" />
    </Type>
  </Table>
  <Table Name="dbo.students" Member="students">
    <Type Name="student">
      <Column Name="VoteId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CandidateId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VotingTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CandidateName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Association Name="Candidate_student" Member="Candidate" ThisKey="CandidateId" OtherKey="CandidateId" Type="Candidate" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="registeration_student" Member="registeration" ThisKey="Id" OtherKey="Id" Type="registeration" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Winners" Member="Winners">
    <Type Name="Winner">
      <Column Name="WinnerId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CandidateId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CandidateName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="VoteCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ElectionDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Candidate_Winner" Member="Candidate" ThisKey="CandidateId" OtherKey="CandidateId" Type="Candidate" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Feedback2" Member="Feedback2s">
    <Type Name="Feedback2">
      <Column Name="FeedbackId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="FeedbackText" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="TimeSubmitted" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="registeration_Feedback2" Member="registeration" ThisKey="UserId" OtherKey="Id" Type="registeration" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UpcomingElections" Member="UpcomingElections">
    <Type Name="UpcomingElection">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CandidateName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Age" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VotingTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Party" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="VotingSign" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.UpcomingElectionspk44" Member="UpcomingElectionspk44s">
    <Type Name="UpcomingElectionspk44">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CandidateName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Age" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VotingTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Party" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="VotingSign" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>